### ISSUE TITLE
Historical quotes doesn't work

### ISSUE THREAD

**Issue by rightedges** [herval/yahoo-finance#42]
This was fine before. Did Yahoo just block the connection?

```
$ irb
2.1.10 :001 > require 'yahoo-finance'
 => true 
2.1.10 :002 > yahoo_client = YahooFinance::Client.new
 => #<YahooFinance::Client:0x007fe05c8826a8> 
2.1.10 :003 > data = yahoo_client.quotes(["BVSP", "NATU3.SA", "USDJPY=X"], [:ask, :bid, :last_trade_date])
 => [#<OpenStruct ask="N/A", bid="N/A", last_trade_date="N/A", symbol="BVSP">, #<OpenStruct ask="35.30", bid="34.85", last_trade_date="5/16/2017", symbol="NATU3.SA">, #<OpenStruct ask="112.4120", bid="112.4110", last_trade_date="5/17/2017", symbol="USDJPY=X">] 
2.1.10 :004 > data = yahoo_client.historical_quotes("AAPL")
OpenURI::HTTPError: 502 Connection refused
	from /Users/william/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/open-uri.rb:353:in `open_http'
	from /Users/william/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/open-uri.rb:724:in `buffer_open'
	from /Users/william/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/open-uri.rb:210:in `block in open_loop'
	from /Users/william/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/open-uri.rb:208:in `catch'
	from /Users/william/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/open-uri.rb:208:in `open_loop'
	from /Users/william/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
	from /Users/william/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/open-uri.rb:704:in `open'
	from /Users/william/.rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/open-uri.rb:34:in `open'
	from /Users/william/.rvm/gems/ruby-2.1.10/gems/yahoo-finance-1.2.1/lib/yahoo-finance.rb:207:in `read_historical'
	from /Users/william/.rvm/gems/ruby-2.1.10/gems/yahoo-finance-1.2.1/lib/yahoo-finance.rb:150:in `historical_quotes'
	from (irb):4
	from /Users/william/.rvm/rubies/ruby-2.1.10/bin/irb:11:in `<main>'
```

**Comment by rightedges** [comment]
Hit `https://ichart.finance.yahoo.com/table.csv?aapl` and return with 

![screen shot 2017-05-17 at 11 39 06 am](https://cloud.githubusercontent.com/assets/5228138/26137529/4954dfaa-3af5-11e7-9783-9411496d79ea.png)

Temporary problem I hope.

**Comment by bernulander** [comment]
Is the service actually coming back? I haven't been able to find any information.

**Comment by william0901** [comment]
Nope. It's dead.

**Comment by cpankaj** [comment]
For alternate solution look at 
https://github.com/cpankaj/yquotes
Seems to be working for historical quotes

**Comment by philss** [comment]
Yes, it's offline as we can see in [here](https://forums.yahoo.net/t5/Yahoo-Finance-help/ichart-not-working-in-my-app/td-p/253560).

There is an workaround suggested in https://github.com/lukaszbanasiak/yahoo-finance/issues/128, which is to get from the Yahoo Finance HTML page.

Example of a page for the ticker `^BVSP`: https://finance.yahoo.com/quote/%5EBVSP/history?period1=1483236000&period2=1496113200&interval=1d&filter=history&frequency=1d

**Comment by lukaszbanasiak** [comment]
More details here https://github.com/lukaszbanasiak/yahoo-finance/issues/128#issuecomment-304482430

**Comment by jkbailey** [comment]
Here is some code to parse html for history

```def get_history(symbol)
  data = []
  url = "https://finance.yahoo.com/quote/#{symbol}/history/"
  doc = Nokogiri::HTML(open(url))
  rows = doc.xpath("//table")[1].css('tr')

  cols = rows[0].css('th').to_a
  close_col = cols.index{|c| c.text == 'Close'}

  rows.each do |each_row|
    divs = each_row.css('td')
    if divs[1] && divs[1].text != 'Dividend' #Ignore this row in the table
      data << {
        'date': Date.parse(divs[0].text),
        'price': divs[close_col].text.to_f
      }
    end
  end

  data
end```

**Comment by bernulander** [comment]
@jkbailey Hey man, I've been using your code, thanks a lot btw! I was wondering if you could help me. How would you make a request with an specific timeframe or a fetch since the beginning of time instead of only the default timeframe. Thanks in advance! hope you can help me!

**Comment by jkbailey** [comment]
You're welcome @bernulander :)

As far as getting a specific timeframe it looks like you should use a url with two timeperiods (ie. `https://finance.yahoo.com/quote/#{symbol}/history?period1=1439017200&period2=1502175600&interval=1d&filter=history&frequency=1d)`)

Hopefully that helps!
